### ISSUE TITLE
Not playing weather report

### ISSUE THREAD

**Issue by ScottChapman** [n0bel/PiClock#20]
Might be an issue with my pi config, but I am not getting audio when using weather from [Worcester MA](http://audioplayer.wunderground.com/CW5897/Auburn.mp3)

**Comment by n0bel** [comment]
Audio problems over HDMI can usually be solved by the solutions in this post:

https://www.raspberrypi.org/forums/viewtopic.php?t=5062

**Comment by ScottChapman** [comment]
Not running audio over HDMI, just (for now) plugged in speaker to audio port.

My issue *might* be related to the audio URL for my location (which appears to be different than most off the others since it appears to be an MP3).

That's why I posted.

**Comment by n0bel** [comment]
Your URL works fine here.

In that case look at this:

https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=40872

Which gives a possible solution, add a line after 21 in startup.sh
sudo amixer cset numid=3 1

sudo amixer cset numid=3 <output>

0=auto
1=headphones
2=hdmi

**Comment by ScottChapman** [comment]
Yea, so maybe I am doing something wrong. I tried that line in my startup. I also verified that speaker_test works (which it does). But I am still not getting the forecast to play.

Any other ideas?

**Comment by n0bel** [comment]
Does it play manually?
The command is:
```
mpg123 http://audioplayer.wunderground.com/CW5897/Auburn.mp3
```

**Comment by ScottChapman** [comment]
Yes.

**Comment by n0bel** [comment]
Does it work when you press the F2 on a keyboard connected to the pi?

**Comment by ScottChapman** [comment]
No it does not. I've attached my Config.py file
[Config.py.zip](https://github.com/n0bel/PiClock/files/398411/Config.py.zip)

**Comment by n0bel** [comment]
There may not be anything revealing, but reboot, do an F2, wait about 30 seconds, to be sure its still failing.   Then use F4 to close the clock.   Then review the log files.   Look at the log file with the latest date/time.  ls -ltr PiClock/Clock/*.log

**Comment by n0bel** [comment]
I deleted the previous comment since you have your lat/lon in it.

**Comment by ScottChapman** [comment]
OK, I see this in the logs:

Traceback (most recent call last):
  File "PyQtPiClock.py", line 556, in keyPressEvent
    weatherplayer = Popen(["mpg123","-q",  Config.noaastream ])
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by n0bel** [comment]
somehow you skipped the following in the instructions:

##Get mpg123 (optional to play NOAA weather radio streams)
(you must still be root [super user])
```
apt-get install mpg123
```

At this point just do:

```
sudo apt-get install mpg123
```

**Comment by ScottChapman** [comment]
Boom.

Not sure how I missed it. Thanks!

**Comment by n0bel** [comment]
great!

**Comment by n0bel** [comment]
NOAA weather radio streams have reappeared on the net.  You can find it here: http://noaaweatherradio.org/ They don't put the .mp3 urls where they are easily accessable, so you need to use your browser to "View Page Source" in order to find the proper .mp3 url.
